FROM node:22

WORKDIR /app

COPY service/ .

# install and configure pnpm
RUN npm install -g pnpm
ENV PNPM_HOME=/root/.pnpm
ENV PATH=$PNPM_HOME:$PATH

RUN pnpm install
RUN pnpm add -g tsx

CMD ["tsx", "index.ts"]
